### ISSUE TITLE
When using this player below android 11 then it is working fine but when using it in android 11 devices a different player is showing

### ISSUE THREAD

**Issue by affan00733** [LonelyCpp/react-native-youtube-iframe#190]
When using this player below android 11 then it is working fine but when using it in android 11 devices a different player is showing

What can we do

**Comment by Demonbruster** [comment]
Yeah I used  mi phone and huawei phone then i got two different layout. 😞
How to solve this one @LonelyCpp

**Comment by affan00733** [comment]
Yes please tell fast how to solve it

**Comment by LonelyCpp** [comment]
The player UI is decided by the YouTube script and this library has no control over it.

you can try tricking the script using different userAgent strings - 

```jsx
<YoutubePlayer
  webViewProps={{ userAgent: 'user-agent-string' }}
/>
```

you can find user agent strings here : https://deviceatlas.com/blog/list-of-user-agent-strings

---

generally, you should not rely on the YouTube UI in the player since it's entirely controlled by YouTube and they offer no customisations on top of it.

**Comment by affan00733** [comment]
how and which user agent string can you tell me in detail

**Comment by LonelyCpp** [comment]
You would have to try them yourself by trial and error, and use whatever works for you.

**Comment by affan00733** [comment]
but what is user-agent-string can give an example

**Comment by LonelyCpp** [comment]
Example : `Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36`

As mentioned, you'll find more info here : https://deviceatlas.com/blog/list-of-user-agent-strings
