### ISSUE TITLE
Closed captioning not appearing in fullscreen mode

### ISSUE THREAD

**Issue by tordog** [LonelyCpp/react-native-youtube-iframe#199]
**Describe the bug**
Closed captioning shows up when video is displayed inline, but disappears when changed to fullscreen. The bottom bar of the video also does not show the closed captioning icon in fullscreen, but it's there and selectable when played inline.

**To Reproduce**
Play video inline. Enable closed captioning for the video via bottom bar. Expand to fullscreen

Code: 
`import YoutubePlayer from 'react-native-youtube-iframe';

<YoutubePlayer
      height={height}
      width={width}
      videoId={videoID}
      onChangeState={onStateChange}
      webViewProps={{
        scrollEnabled: false,
      }}
    />`

**Expected behavior**
When opening a video in fullscreen with closed captioning on, the closed captioning should still display
Closed captioning options should also display in the bottom bar in fullscreen mode

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS + version: iOS 14.7.1
 - `react-native-youtube-iframe` version ^1.4.2
 - `react-native-webview` version ^11.3.2
 - `Expo` verison [if using expo]

**Comment by LonelyCpp** [comment]
It looks like the safari fullscreen subtitle bug has been around for a long time, and hasn't been fixed by apple or google yet.

some discussions I found online : 
- https://discussions.apple.com/thread/252652051
- https://github.com/videojs/video.js/issues/6640

since the closed captioning is fully handled by youtube's player, this library can't practically do anything about it :(

I'm open to suggestions tho, so if you have any leads please let me know.
