### ISSUE TITLE
View Count Incrementation

### ISSUE THREAD

**Issue by b-a-merritt** [LonelyCpp/react-native-youtube-iframe#222]
Does playing a video using this API increment the view count of that video? 
There seems to be little information about this from the research I've done. 
I found a couple references, but

this post is outdated and refers to autoplay (which I'm not doing)
https://stackoverflow.com/questions/13456288/does-youtube-api-play-function-trigger-a-view-count

and this one only refers to embed on the web
https://support.google.com/youtube/thread/23699221/does-view-count-increases-on-youtube-when-the-user-viewed-the-embed-video-from-another-site?hl=en

Using the "external" portion of YouTube's analytics seems like a possible way to test this, 
but (1) I don't currently have access to the content provider's analytics,
(2) I'm not sure exactly what information is displayed there,
and (3) making a YouTube account, creating videos, and testing them on my app seems overkill if someone here knows the answer.
https://support.google.com/youtube/answer/9314355?hl=en

If there's no response to this thread in a bit, then I'll try testing with the analytics

If does not currently increment the view count, would it be possible to add this feature? 
It seems like an important feature, especially when YouTube content creators get paid based on them.

**Comment by LonelyCpp** [comment]
Hey I'm sorry man, I'm as clueless as you are. 

It would not be possible to get a concrete answer to this unless there's some explicit documentation about this OR have some YouTube employee answer this.

This library only abstracts the public API, and anything that is not available in the [official docs](https://developers.google.com/youtube/iframe_api_reference) cannot be added as a feature. 

I'll close this since this is not directly related to the iframe abstraction in this library, but rather a general YouTube iframe question, but feel free up update this ahead if you find anything :)
