### ISSUE TITLE
ios stability issue

### ISSUE THREAD

**Issue by mtalhagaoglu** [LonelyCpp/react-native-youtube-iframe#24]
hi. i have problems with ios devices. on android there is no problem btw.

i tried with two android and two ios devices. For example on same network, ios devices start video 1 min (sometimes less but avarage it 1 min) later. takes too much time to buffer. i thought the issue was network but it's not.

**Comment by LonelyCpp** [comment]
Hey!
How long does the `onReady` callback take? The video quality is set to best suit your network and there is no way to make it configurable.  The delta between `onReady` and the `playing` event is entirely up to YouTube.

[source](https://developers.google.com/youtube/iframe_api_reference#october-24,-2019)
>to give you the best viewing experience, YouTube adjusts the quality of your video stream based on your viewing conditions.

I've tested it on an iPhone 11 and it seemed to work fine, what phone are you testing yours on?

**Comment by mtalhagaoglu** [comment]
i tested with ip6 and ip7. I'm trying to do control YouTube actions remotly. you can think like YouTube or netflix party. all the viewers should be at the same second but ios devices always lagging behind. i couldn't fix that problem :/ do you have any idea?

**Comment by LonelyCpp** [comment]
Sure. I'm assuming you have a server to control the party.

* You can first wait for all devices in the party to fire the `playing` event from `onChangeState` callback. (the client will have to stop the video immediately after the `playing` event and wait for other clients)
* This will make sure all clients have buffered and are ready to play. Lets call this `partyReady`
* When the server knows all clients are ready to go, it notifies the client to start playing at a particular time stamp (say 5 seconds from `partyReady`) 
* since it will be a timestamp, all clients will start playing at the exact same time, completely in sync.

**Comment by mtalhagaoglu** [comment]
i am using firebase listeners for sending and receiving start stop and seek commands. it's works enough for me but YouTube doesn't start as it's supposed to be. if i have limited client, i can do what you said (wait all the clients to be ready) but i have for example 1000+ client. i can't wait all of them to be ready. it will take too much time

**Comment by LonelyCpp** [comment]
of course, you're right. 
But the iframe API handles the buffering and quality 😞  You have to figure out some work around to account for this buffer. 

You could check if this approach work for smaller connected clients though. Do you already have an app that has 1000+ clients synced? if not, its work a shot

**Comment by mtalhagaoglu** [comment]
i don't have that much user now but it can be that much in the future (i hope). thanks for your help i will try what did you say. if you want you can close issue. if i find anything good i will update.
