### ISSUE TITLE
Player in offline mode never triggers onError

### ISSUE THREAD

**Issue by tcorreiaubi** [LonelyCpp/react-native-youtube-iframe#35]
**Describe the bug**
I'm trying to handle scenarios where the user navigates to a screen where the player is being used and for some reason the video fails to load or is there a network failure such as, for example the wifi being down, I expected the onError to trigger but somehow it never does

**To Reproduce**
```javascript
<YoutubePlayer
    onError={() => {
        console.log('###### Error loading video #######')
    }}
    onReady={() => console.log('############# ready ################')}
    onChangeState={event => console.log('s######  state change ###### ', event)}
    play
    webViewStyle={Styles.videoPlayer}
    videoId={videoId}
    webViewProps={{
        onHttpError: () => {
            console.log('###### on onHttpError from webview #######')
        },
        onError: () => {
            console.log('###### on Error from webview #######')
        },
    }}
/>
```

**Expected behavior**
I expected the onError to trigger if for some reason the video failed to load

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 lite
 - OS + version: Android 8.0.0
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 10.2.3
 - `react-navite` 0.59.9

**Comment by LonelyCpp** [comment]
Hi, so the `onError` callback is for player errors, so there are for errors that come up after the player has been loaded.

You will not get error callbacks from the webview either since the player is loaded into place using javascript from [youtube](https://www.youtube.com/iframe_api). There isn't a way to detect script load failures right now unfortunately since that isn't in my control.

Although the only reason the js wouldn't load is due to the device not being connected to the internet. (youtube loads fairly well even in slow networks). You can easily handle this using [netinfo](https://github.com/react-native-community/react-native-netinfo)

**Comment by tcorreiaubi** [comment]
@LonelyCpp I believe that's a solution, thanks for the information, was enough to understand why the callbacks where not being triggered
