### ISSUE TITLE
Prevent from switching to Youtube app on iOS

### ISSUE THREAD

**Issue by federicomiralles** [LonelyCpp/react-native-youtube-iframe#39]
**Describe the bug**
When playing a video on fullscreen and going back to normal mode (inline), after resuming the video instead of keep showing the video from where it was left, the user is taken to the youtube app video channel on iOS...

**To Reproduce**
Check to code below on an iPhone XR with version 13.5.1

**Expected behavior**
To resume the video within the app as opposed to switching to youtube app video channel

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS + version: iOS 13.5.1
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 10.3.1
 - `react-native` 0.62.2

**Additional context**
```
<YoutubePlayer
          play={playing}
          height={75}
          width={150}
          videoId={YOUTUBE_VIDEO_ID}
          webViewProps={{
            allowsInlineMediaPlayback: false,
            allowsFullscreenVideo: true,
          }}
          onChangeState={state => {
            if (state === 'paused' || state === 'ended') {
              setPlaying(false);
            }
          }}
          initialPlayerParams={{
            modestbranding: true,
          }}
        />
```

**Comment by LonelyCpp** [comment]
Hi @federicomiralles,

From what I can gather, clicking on the channel icon on top of the video redirects the user to the youtube app. This is intentional behaviour. Since your player window is tiny (75x150), the tap on the player is picked up by the channel link on top.

p.s It is recommended that players be at least 480 pixels wide and 270 pixels tall. Publishing apps that don't follow this is in violation of the [youtube ToS](https://developers.google.com/youtube/terms/required-minimum-functionality#embedded-youtube-player-size).
