### ISSUE TITLE
Fullscreen control is hide on small width devices.

### ISSUE THREAD

**Issue by nirmal25990** [LonelyCpp/react-native-youtube-iframe#41]
**Describe the bug**
The fullscreen control button is showing on small size devices like iPhone 6, 8(The main issue is small screen width not the device). **Getting an issue in iPhone only** as in the android progress bar is at the bottom after time, volume, and full-screen button so no issue. 

**To Reproduce**
In the YoutubePlayer(In iPhone device/simulator) If set `height={180}` and `width={348}` fullscreen button is showing but if reduce the width to `width={328}` at that time it will not show.

**Expected behavior**
Is there any workaround that I can show play/push button, progress bar/playtime, and fullscreen button only. Basically user can play video in fullscreen mode as well.

**Screenshots**
Working example(iPhone 8+)
<img width="293" alt="Screen Shot 2020-07-08 at 3 55 27 PM" src="https://user-images.githubusercontent.com/9558491/86918974-16f0b780-c145-11ea-8a14-773cb2fa678f.png">

Not working example(iPhone 8)
<img width="286" alt="Screen Shot 2020-07-08 at 3 55 20 PM" src="https://user-images.githubusercontent.com/9558491/86919079-456e9280-c145-11ea-81a5-bb049fdeb069.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone8/8+]
 - OS + version: [iOS 13.5]
 - `react-native-youtube-iframe` version 1.2.4 
 - `react-native-webview` version 10.3.1
 - `Expo` verison [not using expo]

**Additional context**
No.

**Sample code**
```
<YoutubePlayer
 height={180}
 width={348}
 videoId={'## video id ##'}
 onChangeState={event => console.log(event)}
 onReady={() => console.log('ready')}
 onError={e => console.log(e)}
 onPlaybackQualityChange={q => console.log(q)}
 volume={50}
 playbackRate={1}
 playerParams={{
  cc_lang_pref: 'us',
  showClosedCaptions: true,
  allowSeekAhead: false //to hide seek control
 }}
/>
```

**Comment by LonelyCpp** [comment]
hi @nirmal25990 

This is expected behaviour by the youtube player to accommodate the time scrubber. It is recommended that players be at least **480 pixels wide** and 270 pixels tall . The video player will not have enough space in small widths like you mentioned.

iOS controls are rendered by the HTML5 player in safari wkwebview. You can expect this behaviour for any video played on a webview with such widths. Only work around I see here is to decrease card margin to give the player a wider view port.

p.s: Publishing apps that don't follow this is in violation of the [youtube ToS](https://developers.google.com/youtube/terms/required-minimum-functionality#embedded-youtube-player-size).

**Comment by LonelyCpp** [comment]
> Is there any workaround that I can show play/push button, progress bar/playtime, and fullscreen button only. Basically user can play video in fullscreen mode as well.

unfortunately we cannot control this ☹️ The player is inside an iframe that belongs to youtube so we will not be able to manipulate anything in it (CORS)

**Comment by soundaraj** [comment]
allowSeekAhead not work for me

**Comment by LonelyCpp** [comment]
@soundaraj `allowSeekAhead` is not a supported key. 

Here is the full list of supported keys for [initialPlayerParams](https://lonelycpp.github.io/react-native-youtube-iframe/component-props#initialplayerparams)
