### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by fajarazay** [LonelyCpp/react-native-youtube-iframe#49]
**Describe the bug**
<img width="1405" alt="Screen Shot 2020-07-28 at 09 13 49" src="https://user-images.githubusercontent.com/14243792/88611165-a806de80-d0b2-11ea-8b4f-4fd6e9d7c6a4.png">

**To Reproduce**
Upload to appstore, would received feedback from apple.
**Expected behavior**
Should replace UIWebView by WKWebView
**Screenshots**

**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe`1.2.4 
 - `react-native-webview` 10..3.2
 - `Expo` verison [if using expo]

**Additional context**

**Comment by LonelyCpp** [comment]
hi @fajarazay 

`react-native-webview` has completely removed UIWebView since version `7.0.1` - [release notes](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1)

Since you're using `10.3.2`, it's safe to say that the deprecation is not coming from `react-native-webview`. It's probably some other package that might be using UIWebView internally.

**Comment by LonelyCpp** [comment]
If you were using on older version previously, make sure you've installed the node packages correctly and run `pod update` in the ios folder.
