### ISSUE TITLE
Fullscreen enabled on iOS but disabled on Android

### ISSUE THREAD

**Issue by TimMun** [LonelyCpp/react-native-youtube-iframe#6]
For all of the videos I've tried, the fullscreen button is enabled on iOS but disabled on Android. Sample code below:

```
<YoutubePlayer
            videoId={"c8deRYotdng"} // The YouTube video ID
            play
            onError={this.onYoutubeError}
            height={height + 20}
            width={screenWidth + 20}
            initialPlayerParams={{
              preventFullScreen: false,
              iv_load_policy: 3, 
              modestbranding: 1,
              rel: 0
            }}
          />
```

**Comment by LonelyCpp** [comment]
Hey, just to be clear - you want it disabled, right?

**Comment by TimMun** [comment]
Oh no, I'm trying to get it enabled on both platforms. Strange that the behavior is different.

**Comment by LonelyCpp** [comment]
This is because fullscreen is disabled by default in android webviews. You need to pass in  in webviewProps like so - 
```
webViewProps={{ allowsFullscreenVideo: true }}
```

more info [here](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#webViewProps) and [here](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#allowsfullscreenvideo)

I will link this in with the `preventFullScreen` key by default  in a future update. Thanks :)

**Comment by TimMun** [comment]
Ah, you're right. Thanks alot!
